name: Run C++ tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install g++ -y

      - name: Compile tests
        run: g++ -std=c++17 -o test_list test_list.cpp list.cpp

      - name: Run tests
        run: ./test_list
